[window]
  padding = { x = 3, y = 3 }
  dynamic_padding = true
  decorations = 'Buttonless'
  opacity = 0.9
  option_as_alt = 'OnlyLeft'

[colors]
  transparent_background_colors = true
  draw_bold_text_with_bright_colors = true

[colors.normal]
  black = '#282b33'
  red = '#d17277'
  green = '#a0c180'
  yellow = '#dfc184'
  blue = '#73ade9'
  magenta = '#bb7bd7'
  cyan = '#6fb3bf'
  white = '#acb1bd'

[colors.bright]
  black = '#676767'
  red = '#e57270'
  green = '#9fc080'
  yellow = '#fefb7e'
  blue = '#6f95f7'
  magenta = '#f07ef8'
  cyan = '#6fb3bf'
  white = '#feffff'

[keyboard]
bindings = [
  { key = 'Left', mods = 'Alt', chars = "\u001bB" },
  { key = 'Right', mods = 'Alt', chars = "\u001bF" },
  { key = 'Left', mods = 'Command', chars = "\u001bOH" },
  { key = 'Right', mods = 'Command', chars = "\u001bOF" },
  { key = 'Back', mods = 'Command', chars = "\u0015" },
]
