start-at-login = true
after-login-command = []
after-startup-command = []
key-mapping.preset = 'qwerty'

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'
accordion-padding = 20

on-focus-changed = 'move-mouse window-lazy-center'
on-focused-monitor-changed = 'move-mouse window-lazy-center'

[gaps]
inner.horizontal = [{ monitor.'Built-in Retina Display' = 5 }, 10]
inner.vertical = [{ monitor.'Built-in Retina Display' = 5 }, 10]
outer.left = [{ monitor.'Built-in Retina Display' = 0 }, 10]
outer.bottom = [{ monitor.'Built-in Retina Display' = 0 }, 10]
outer.top = [{ monitor.'Built-in Retina Display' = 0 }, 10]
outer.right = [{ monitor.'Built-in Retina Display' = 0 }, 10]

[mode.main.binding]
# Preferred layouts, the main window is always on the left
alt-cmd-ctrl-shift-t = [ # fullscreen, keep focus
    'flatten-workspace-tree',
    'layout h_accordion',
]
alt-cmd-ctrl-shift-r = [ # bsp, up to 4 windows, focus main
    'flatten-workspace-tree',
    'layout h_tiles',
    'focus --dfs-index 0',
    'move left',
    'focus --dfs-index 3',
    'join-with up',
    'focus --dfs-index 1',
    'focus --dfs-index 0',
]
alt-cmd-ctrl-shift-e = [ # two columns, focus secondary
    'flatten-workspace-tree',
    'layout v_accordion',
    'focus --dfs-index 0',
    'move left',
    'focus-back-and-forth',
]
alt-cmd-ctrl-shift-w = [ # columns (default), keep focus
    'flatten-workspace-tree',
    'layout h_tiles',
]
alt-cmd-ctrl-shift-q = [ # make main, up to 4 windows
    'focus --dfs-index 0',
    'move right',
    'focus-back-and-forth',
    'move left',
    'move left',
    'move left',
]

# Switch focus by position
alt-cmd-ctrl-shift-tab = 'focus right --boundaries-action wrap-around-the-workspace'
alt-cmd-ctrl-shift-space = 'focus down --boundaries-action wrap-around-the-workspace'

# Switch focus by app
alt-cmd-ctrl-shift-f = 'exec-and-forget open -a Arc'
alt-cmd-ctrl-shift-d = 'exec-and-forget open -a Ghostty'
alt-cmd-ctrl-shift-s = 'exec-and-forget open -a Slack'
alt-cmd-ctrl-shift-a = 'exec-and-forget open -a "Visual Studio Code"'

# Open other apps and locations
alt-cmd-ctrl-shift-v = 'exec-and-forget $HOME/.config/aerospace/bin/move_arc D'
alt-cmd-ctrl-shift-c = 'exec-and-forget $HOME/.config/aerospace/bin/tmux_session_selector'
alt-cmd-ctrl-shift-x = 'exec-and-forget open -a "Cisco Secure Client"'
alt-cmd-ctrl-shift-z = 'exec-and-forget code $HOME/repos/local/tax-material'

# Navigate workspaces
alt-f = 'workspace F'
alt-d = 'workspace D'
alt-s = 'workspace S'
alt-tab = 'workspace-back-and-forth'
alt-shift-f = 'move-node-to-workspace --focus-follows-window F'
alt-shift-d = 'move-node-to-workspace --focus-follows-window D'
alt-shift-s = 'move-node-to-workspace --focus-follows-window S'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Resize windows
alt-equal = 'resize smart +50'
alt-minus = 'resize smart -50'

# Layers
alt-shift-p = 'mode position'

[mode.position.binding]
esc = ['reload-config', 'mode main'] # reload
backspace = 'exec-and-forget $HOME/.config/aerospace/bin/restart_aerospace' # restart

# Switch focus by index
1 = ['focus --dfs-index 0', 'mode main']
2 = ['focus --dfs-index 1', 'mode main']
3 = ['focus --dfs-index 2', 'mode main']
4 = ['focus --dfs-index 3', 'mode main']

# Move
h = ['move left', 'mode main']
j = ['move down', 'mode main']
k = ['move up', 'mode main']
l = ['move right', 'mode main']
tab = [
    'move-node-to-monitor --focus-follows-window --wrap-around next',
    'mode main',
]

# Switch layout
f = ['layout floating tiling', 'mode main']
v = ['layout vertical horizontal', 'mode main']

# Callbacks
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

# Assingn apps to workspaces (F for browsing, D for coding, S for messaging)
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser' # Arc
run = 'move-node-to-workspace F'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty' # Ghostty
run = 'move-node-to-workspace D'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode' # Visual Studio Code
run = 'move-node-to-workspace D'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap' # Slack
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook' # Outlook
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'us.zoom.xos' # Zoom
run = 'move-node-to-workspace S'

# Throw far far away
[[on-window-detected]]
if.app-id = 'com.cisco.secureclient.gui' # VPN
run = ['layout floating', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel' # Excel
run = 'move-node-to-workspace X'
