export PATH="$HOME/.local/bin:$PATH"
export WORK_DIR="$HOME/repos"
export EDITOR='nvim'
export PICKER_CMD='FzfLua files';

[[ -f "$HOME/.config/bash/prompt" ]] && source "$HOME/.config/bash/prompt"
[[ -f "$HOME/.config/bash/aliases" ]] && source "$HOME/.config/bash/aliases"
